# Generated by Django 3.1.5 on 2021-05-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_user',
        ),
    ]
