# Generated by Django 3.1.5 on 2021-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
